;;; meetup.el --- meetup integration                 -*- lexical-binding: t; -*-

;; Copyright (C) 2014  Nic Ferrier

;; Author: Nic Ferrier <nferrier@ferrier.me.uk>
;; Keywords: calendar

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; Sync meetup.com with org-mode.

;;; Code:

(require 'web)
(require 'shadchen)
(require 'dash)

(defconst meetup-url
  "http://www.meetup.com/events/rss/28515762/bb5fded36fe53b5e92bde2fa5c91a94e379060df/going"
  "The URL of the Meetup meetings.")

(defconst meetup-icalendar-url
  "http://www.meetup.com/events/ical/28515762/bb5fded36fe53b5e92bde2fa5c91a94e379060df/going"
  "The URL of the ICalendar Meetup meetings.")

(defconst meetup-org-file
  "~/work/org/meetup.org"
  "The org-file where we save the meetup events.")

(defun meetup/item-data (item)
  (match
   item
   ((cons 'item (cons _ (alist
                         'guid (list _ guidref)
                         'description (funcall (lambda (l) (find-if 'stringp l)) desc)
                         'pubdate (list a datestr))))
    (list guidref desc datestr))))

(defun meetup/get ()
  (web-http-get
   (lambda (con hdr data)
     (let* ((rss
             (with-temp-buffer
               (insert data)
               (libxml-parse-html-region (point-min) (point-max))))
            (item-data
             (match 
              rss
              ((list
                'html _
                (list
                 'body _
                 (list 'rss
                       (list (cons 'version "2.0"))
                       (list 'channel _ (tail data))))) data)))
            (lastbuild (kva 'lastbuildate item-data))
            (items (--filter (eq (car it) 'item) item-data)))
       (setq meetup-items 
             (-keep 'meetup/item-data items))))
   :url meetup-url))

(defun meetup/get-to-diary-form ()
  ;; This sucks because diary sucks
  (web-http-get
   (lambda (con hdr data)
     (let ((file (make-temp-name "/tmp/meetup"))
           (coding-system-for-write 'raw-text))
       (with-temp-file file
         (insert data))
       (icalendar-import-file file "~/work/org/meetup-diary")
       (kill-buffer (find-file-noselect file))))
   :url
   "http://www.meetup.com/events/ical/28515762/bb5fded36fe53b5e92bde2fa5c91a94e379060df/going"))


(defun meetup/parse-ical (ical-buffer)
  "Return nil or the list of VEVENTS in ICAL-BUFFER.

Each VEVENT is returned as a list of: 

  uid, event start time, summary, url

The event start time is a string of YYYYmmDDHHMMSS.  The uid may
be any unique identifier.  The summary and url are both
un-escaped."
  (when (re-search-forward "^BEGIN:VCALENDAR\\s-*$" nil t)
    (let (ical-contents ical-errors)
      ;; read ical
      (beginning-of-line)
      ;; Return the list of items
      (--map
       (match
        it
        ((list
          'VEVENT _
          (alist 'DTSTART (list (list 'TZID _) tstart)
                 'SUMMARY (list _ title)
                 'URL (list _ url)
                 'UID (list _ uid)) _)
         (list uid tstart
               (icalendar--convert-string-for-import title)
               url)))
       (match
        (icalendar--read-element nil nil)
        ((list
          (list
           'VCALENDAR _
           ical-top-alist
           (funcall (lambda (l) (--filter (eq (car it) 'VEVENT) l))
                    events))) events))))))

(defun meetup/ical-to-org (ical-list)
  "Take ICAL-LIST and make org agenda entries.

ICAL-LIST is as generated by `meetup/ical-parse'."
  (with-current-buffer (get-buffer-create "blah.org")
    (goto-char (point-min))
    (--map
     (match
      it
      ((list uid start summary url)
       (insert
        (s-format
         "* ${start}\n** ${uid}\n** [[${url}][${summary}]]\n"
         'aget
         `((start . ,start)
           (uid . ,uid)
           (url . ,url)
           (summary . ,summary))))))
     ical-list)
    (pop-to-buffer (current-buffer))))


(defun meetup/get-icalendar ()
  (web-http-get
   (lambda (con hdr data)
     (with-temp-buffer
       (insert data)
       (delete-trailing-whitespace (point-min) (point-max))
       (goto-char (point-min))
       (meetup/ical-to-org
        (meetup/parse-ical (current-buffer)))))
   :url meetup-icalendar-url))

;;(meetup/get-icalendar)

(setq meetup/test-data 
      '(("event_209742552@meetup.com" "20141030T183000" "Lies, damn lies and operational metrics" "http://www.meetup.com/DevOps-Exchange-London/events/209742552/")
        ("event_207800592@meetup.com" "20141103T183000" "OpenHack #2" "http://www.meetup.com/OpenHack-London/events/207800592/")
        ("event_203883242@meetup.com" "20141113T190000" "London DevOps Meetup #3" "http://www.meetup.com/London-DevOps/events/203883242/")
        ("event_216111812@meetup.com" "20141113T190000" "HACK ON EMACS!" "http://www.meetup.com/London-Emacs-Hacking/events/216111812/")
        ("event_209183252@meetup.com" "20141202T190000" "London DevOps Meetup #4" "http://www.meetup.com/London-DevOps/events/209183252/")))


(meetup/ical-to-org meetup/test-data)





meetup-parsed

(VCALENDAR nil
           ((VERSION nil "2.0")
            (PRODID nil "-//Meetup//RemoteApi//EN")
            (CALSCALE nil "GREGORIAN")
            (METHOD nil "PUBLISH")
            (X-ORIGINAL-URL nil "http://www.meetup.com/events/ical/28515762/bb5fded36fe53b5e92bde2fa5c91a94e379060df/going")
            (X-WR-CALNAME nil "My Meetups"))
           ((VTIMEZONE nil
                       ((TZID nil "Europe/London")
                        (X-LIC-LOCATION nil "Europe/London"))
                       ((DAYLIGHT nil
                                  ((TZOFFSETFROM nil "+0000")
                                   (TZOFFSETTO nil "+0100")
                                   (TZNAME nil "BST")
                                   (DTSTART nil "19700329T010000")
                                   (RRULE nil "FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU"))
                                  nil)
                        (STANDARD nil
                                  ((TZOFFSETFROM nil "+0100")
                                   (TZOFFSETTO nil "+0000")
                                   (TZNAME nil "GMT")
                                   (DTSTART nil "19701025T020000")
                                   (RRULE nil "FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU"))
                                  nil)))
            (VEVENT nil
                    ((DTSTAMP nil "20141029T235049Z")
                     (DTSTART
                      (TZID "Europe/London")
                      "20141030T183000")
                     (DTEND
                      (TZID "Europe/London")
                      "20141030T210000")
                     (STATUS nil "CONFIRMED")
                     (SUMMARY nil "Lies\\, damn lies and operational metrics")
                     (DESCRIPTION nil "DevOps Exchange - London\\nThursday\\, October 30 at 6:30 PM\\n\\nTorkel \303\226degaard (Creator of Grafana) & Paul Dix (Founder InfluxDB) - Grafana + InfluxDB = Awesome Monitoring Torkel \303\226degaard (Creator of Grafana) & Pa...\\n\\nDetails: http://www.meetup.com/DevOps-Exchange-London/events/209742552/")
                     (CLASS nil "PUBLIC")
                     (CREATED nil "20140926T212941Z")
                     (GEO nil "51.50;-0.07")
                     (LOCATION nil "Central Foundation Boys School (Cowper Street\\, London\\, EC2A 4SH\\, London\\, United Kingdom)")
                     (URL nil "http://www.meetup.com/DevOps-Exchange-London/events/209742552/")
                     (LAST-MODIFIED nil "20141021T173449Z")
                     (UID nil "event_209742552@meetup.com"))
                    nil)
            (VEVENT nil
                    ((DTSTAMP nil "20141029T235049Z")
                     (DTSTART
                      (TZID "Europe/London")
                      "20141103T183000")
                     (DTEND
                      (TZID "Europe/London")
                      "20141103T213000")
                     (STATUS nil "CONFIRMED")
                     (SUMMARY nil "OpenHack #2")
                     (DESCRIPTION nil "OpenHack London\\nMonday\\, November 3 at 6:30 PM\\n\\nWe meet on the first Monday of the month at 6:30-9:30 pm. This month we're at: uSwitch Limited Notcutt House 36 Southwark Bridge Road London SE1 9EU\\n\\nDetails: http://www.meetup.com/OpenHack-London/events/207800592/")
                     (CLASS nil "PUBLIC")
                     (CREATED nil "20140917T143922Z")
                     (GEO nil "51.45;-0.02")
                     (LOCATION nil "uSwitch Limited (Notcutt House 36 Southwark Bridge Road London SE1 9EU\\, London\\, United Kingdom)")
                     (URL nil "http://www.meetup.com/OpenHack-London/events/207800592/")
                     (LAST-MODIFIED nil "20141013T160214Z")
                     (UID nil "event_207800592@meetup.com"))
                    nil)
            (VEVENT nil
                    ((DTSTAMP nil "20141029T235049Z")
                     (DTSTART
                      (TZID "Europe/London")
                      "20141113T190000")
                     (DTEND
                      (TZID "Europe/London")
                      "20141113T220000")
                     (STATUS nil "CONFIRMED")
                     (SUMMARY nil "London DevOps Meetup #3")
                     (DESCRIPTION nil "London DevOps\\nThursday\\, November 13 at 7:00 PM\\n\\nThis meetup will be in November at the moo.com offices\\, just before Velocity Europe which this year is happening in Barcelona. We will be having three...\\n\\nDetails: http://www.meetup.com/London-DevOps/events/203883242/")
                     (CLASS nil "PUBLIC")
                     (CREATED nil "20140829T091609Z")
                     (GEO nil "51.52;-0.10")
                     (LOCATION nil "moo.com (32-38 Scrutton St\\, London\\, EC2A 4RQ\\, United Kingdom)")
                     (URL nil "http://www.meetup.com/London-DevOps/events/203883242/")
                     (LAST-MODIFIED nil "20140924T135843Z")
                     (UID nil "event_203883242@meetup.com"))
                    nil)
            (VEVENT nil
                    ((DTSTAMP nil "20141029T235049Z")
                     (DTSTART
                      (TZID "Europe/London")
                      "20141113T190000")
                     (DTEND
                      (TZID "Europe/London")
                      "20141113T213000")
                     (STATUS nil "CONFIRMED")
                     (SUMMARY nil "HACK ON EMACS!")
                     (DESCRIPTION nil "London Emacs Hacking\\nThursday\\, November 13 at 7:00 PM\\n\\nJust a sketch\\, while I work out a location.\\n\\nIs the time good?\\n\\nDetails: http://www.meetup.com/London-Emacs-Hacking/events/216111812/")
                     (CLASS nil "PUBLIC")
                     (CREATED nil "20141028T133330Z")
                     (GEO nil "51.50;-0.10")
                     (LOCATION nil "Goldsmiths (New Cross\\, London\\, United Kingdom)")
                     (URL nil "http://www.meetup.com/London-Emacs-Hacking/events/216111812/")
                     (LAST-MODIFIED nil "20141028T133330Z")
                     (UID nil "event_216111812@meetup.com"))
                    nil)
            (VEVENT nil
                    ((DTSTAMP nil "20141029T235049Z")
                     (DTSTART
                      (TZID "Europe/London")
                      "20141202T190000")
                     (DTEND
                      (TZID "Europe/London")
                      "20141202T220000")
                     (STATUS nil "CONFIRMED")
                     (SUMMARY nil "London DevOps Meetup #4")
                     (DESCRIPTION nil "London DevOps\\nTuesday\\, December 2 at 7:00 PM\\n\\nThe special edition meetup will happen again at the Just Eat offices! (Thank you so much guys) We will be having two technical talks (30 mins each) fo...\\n\\nDetails: http://www.meetup.com/London-DevOps/events/209183252/")
                     (CLASS nil "PUBLIC")
                     (CREATED nil "20140924T094905Z")
                     (GEO nil "51.52;-0.10")
                     (LOCATION nil "Just Eat offices (2 Fleet Place\\, London EC4M 7RF\\, United Kingdom)")
                     (URL nil "http://www.meetup.com/London-DevOps/events/209183252/")
                     (LAST-MODIFIED nil "20140924T194851Z")
                     (UID nil "event_209183252@meetup.com"))
                    nil)))


(provide 'meetup)

;;; meetup.el ends here
